### ISSUE TITLE
Enhancement: Wildcarding when authorization challenging

### ISSUE THREAD

**Issue by Okeyja** [Okeyja/active-auth-iam-core#18]
## TODOs

- [x] Wildcarding grantee to represent all challenger(grantee)s, maybe use principal-id=0 as global principal?
- [x] Wildcarding action to represent all actions globally / in one service (like `*` and `bookshelf:*`)
- [x] Wildcarding resources to represent a sub-routed resource.

## Intro

Checking wildcard resource policy on authorization challenging.

Resource priority obeys: `Concrete` > `Abstract`
Owner priority obeys: `Concrete owner regardless resource is concrete or not` > `Abstract owner`
Action priority obeys: `Concrete action regardless owner or resource is concrete or not` > `Abstract action`
Type priority obeys: `DENY` > `ALLOW`
Time priority obeys: `Recent` > `Ancient`
System priority obeys (especially for challenger): `In DB grant` > `In code if-statement condition judgment`.

## Examples

When challenging: 

| name | value |
| ---| ---|
| challenger principal | iam://users/8/principals |
| challenging action | bookshop:getBook |
| challenging resource | bookshelf://users/7/favorite-books/scifi/liucixin/890 |

~~Resources wildcarded by challenging resource are listed below in order of priority:~~

> ~~bookshelf://users/7/favorite-books/scifi/liucixin/890~~
> ~~bookshelf://users/7/favorite-books/scifi/liucixin/\*~~
> ~~bookshelf://users/7/favorite-books/scifi/\*~~
> ~~bookshelf://users/7/favorite-books/\*~~
> ~~bookshelf://users/7/\*~~
> ~~bookshelf://users/\*/favorite-books/scifi/liucixin/890~~
> ~~bookshelf://users/\*/favorite-books/scifi/liucixin/\*~~
> ~~bookshelf://users/\*/favorite-books/scifi/\*~~
> ~~bookshelf://users/\*/favorite-books/\*~~
> ~~bookshelf://users/\*~~

All wildcarded resources in policy are verified in `AND` mode. Supported following examples:

> bookshelf://users/7/favorite-books/scifi/liucixin/890
> bookshelf://users/7/favorite-books/scifi/\*
> bookshelf://users/7/favorite-books/\*/liucixin/\*
> bookshelf://users/\*/favorite-books/scifi/liucixin/890
> bookshelf://users/\*/favorite-books/scifi/\*
> bookshelf://users/\*/favorite-books/\*/liucixin/\*
> bookshelf://users/\*
> bookshelf://\*
> ...

And if the following policy row is inserted in DB:
| name                          | value                                                        |
| ----------------------------- | ------------------------------------------------------------ |
| type                          | Allowed                                                      |
| grantee                       | iam://users/8/principals                                     |
| action                        | bookshop:getBook<br />bookshop:\*<br />\*                    |
| resource | bookshelf://users/7/favorite-books/scifi/\*<br />bookshelf://users/7/favorite-books/scifi/liucixin/\*<br />... |
